Repository Strompy/Crate, pull requests merged in 2020-10, with the labels that each got.

#5 Add github folder and templates to project
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, good first issue

#63 Feature/rw profile page ui
  code/web/public/images/stock/men/4.jpg
  code/web/src/modules/user/Profile.js
  code/web/src/setup/store.js
  code/web/src/ui/image/Tile.js
Labels: FE, Sprint 3, design, enhancement, style, wireframe

#64 Testing/jcs/reducers
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/state.test.js
Labels: FE, Testing

#67 User update details
  code/api/.gitignore
  code/api/src/config/database.json
  code/api/src/modules/subscription/resolvers.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/query.js
  code/api/src/modules/user/resolvers.js
Labels: BE, Sprint 3, enhancement

#74 Feature/abd hook up be to profile
  code/web/public/images/crate-broken.png
  code/web/public/images/stock/men/4.jpg
  code/web/src/modules/common/NotFound.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
Labels: FE, Sprint 4, design, enhancement, style

#77 Sk testing products
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/modules/product/query.test.js
  code/api/src/modules/product/resolvers.js
  code/api/src/setup/database.js
Labels: BE, Chore, Sprint 3, Testing

#80 Feature/rw edit details
  code/package-lock.json
  code/web/src/modules/user/EditProfile.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
Labels: FE, Sprint 4, enhancement

#81 Date subscriptions
  code/api/src/migrations/11-subscriptiondate.js
  code/api/src/modules/subscription/model.js
  code/api/src/modules/subscription/mutations.js
  code/api/src/modules/subscription/resolvers.js
  code/api/src/modules/subscription/types.js
  code/api/src/seeders/4-subscriptions.js
Labels: BE, Sprint 4, enhancement

#82 Feature/jcs/bug squash profile
  .gitignore
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/EditProfile.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.test.js
Labels: FE, Sprint 4, Testing, bug, style

#83 Features/add crate products
  code/api/src/migrations/12-crateProducts.js
  code/api/src/modules/crateProduct/model.js
  code/api/src/modules/crateProduct/mutations.js
  code/api/src/modules/crateProduct/query.js
  code/api/src/modules/crateProduct/resolvers.js
  code/api/src/modules/crateProduct/types.js
  code/api/src/setup/models.js
  code/api/src/setup/schema/mutations.js
  code/api/src/setup/schema/queries.js
Labels: BE, Sprint 4, design, enhancement

#84 Fix naming conventions on migrations. Fix seed file error.
  code/api/src/config/database.json
  code/api/src/migrations/99-userzip.js
  code/api/src/migrations/999-subscriptiondate.js
  code/api/src/seeders/4-subscriptions.js
Labels: BE, Sprint 4, bug

#86 Feature/rw edit shipment date
  code/api/src/config/database.json
  code/api/src/migrations/9999-crateProducts.js
  code/web/public/images/under-construction.png
  code/web/src/modules/subscription/api/actions.js
  code/web/src/modules/subscription/api/state.js
  code/web/src/modules/user/EditProfile.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/orderHistory.js
  code/web/src/setup/routes/user.js
Labels: FE, Sprint 4, enhancement, style
